### ISSUE TITLE
Why create a bespoke queue?

### ISSUE THREAD

**Issue by teaforthecat** [democracyworks/kehaar#49]
https://github.com/democracyworks/kehaar/blob/f8641f384dcbc93b2a040c92887e8a4a65cdc116/src/kehaar/core.clj#L225

@tie-rack  I'm assuming this is so the requestor doesn't have to create a temporary queue, is that right? Also, what is the temporary/bespoke queue solving related to the size of the queue. Is this to soften the load of queue creation? Does a large response stream have potential problems related to the correlation-id some how?

I'm thinking that if a reply-to queue is sent in the request, that should be honored by the response, does that seem reasonable?

**Comment by tie-rack** [comment]
Within a system mediated by kehaar, response queues are managed by kehaar. So, right, the requestor (if we're talking about the Clojure code on the other side of this responder) doesn't create temporary queues ever; whether or not they are created are handled by kehaar behind its interface.

One-off bespoke queues are generally recommended against in RabbitMQ because of the overhead associated with them. Creating a new one for every streaming request would create them too often. Never creating them runs the risk of overwhelming the shared queue when very large responses happen. This threshold system was put into place as a way to have a tune-able balance between those two extremes.

The threshold for a streaming response handler should be set such that, for the most part, responses won't need to move to a new queue. It assumes a distribution of response sizes. Like if 99% of responses will have 10 items or fewer, but a response could have 1,000,000 items, you might set the threshold to 20 so you only catch the extreme outliers.

Until a streaming response's threshold is met, the reply-to queue is honored. Once the threshold is met, a bespoke queue is created and the responder alerts the requester of the new queue. Helpfully, this all happens behind-the-scenes and the client code never knows that this kind of renegotiation of queues took place.

**Comment by teaforthecat** [comment]
excellent description, thanks!
